import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import localFont from 'next/font/local';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});
const robotoB = localFont({
  src: '../../src/app/fonts/robotoB.ttf',
  variable: '--font-robotoB',
});
const robotoR = localFont({
  src: '../../src/app/fonts/robotoR.ttf',
  variable: '--font-robotoR',
});

export const metadata: Metadata = {
  title: 'DEV FELIPE C',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${robotoR.variable} ${robotoB.variable}`}
      >
        <div className='min-h-full mx-auto max-w-7xl !bg-red-700 shadow-2xl'>
          {children}
        </div>
      </body>
    </html>
  );
}
